// flow-typed signature: 54a6991cb634153bc662fde1c4d12a75
// flow-typed version: <<STUB>>/encoding-japanese_v^1.0.29/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'encoding-japanese'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'encoding-japanese' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'encoding-japanese/encoding' {
  declare module.exports: any;
}

declare module 'encoding-japanese/encoding.min' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/banner' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/config' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/encoding-convert' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/encoding-detect' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/encoding-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/index' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/jis-to-utf8-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/jisx0212-to-utf8-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/kana-case-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/utf8-to-jis-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/utf8-to-jisx0212-table' {
  declare module.exports: any;
}

declare module 'encoding-japanese/src/util' {
  declare module.exports: any;
}

declare module 'encoding-japanese/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'encoding-japanese/encoding.js' {
  declare module.exports: $Exports<'encoding-japanese/encoding'>;
}
declare module 'encoding-japanese/encoding.min.js' {
  declare module.exports: $Exports<'encoding-japanese/encoding.min'>;
}
declare module 'encoding-japanese/src/banner.js' {
  declare module.exports: $Exports<'encoding-japanese/src/banner'>;
}
declare module 'encoding-japanese/src/config.js' {
  declare module.exports: $Exports<'encoding-japanese/src/config'>;
}
declare module 'encoding-japanese/src/encoding-convert.js' {
  declare module.exports: $Exports<'encoding-japanese/src/encoding-convert'>;
}
declare module 'encoding-japanese/src/encoding-detect.js' {
  declare module.exports: $Exports<'encoding-japanese/src/encoding-detect'>;
}
declare module 'encoding-japanese/src/encoding-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/encoding-table'>;
}
declare module 'encoding-japanese/src/index.js' {
  declare module.exports: $Exports<'encoding-japanese/src/index'>;
}
declare module 'encoding-japanese/src/jis-to-utf8-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/jis-to-utf8-table'>;
}
declare module 'encoding-japanese/src/jisx0212-to-utf8-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/jisx0212-to-utf8-table'>;
}
declare module 'encoding-japanese/src/kana-case-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/kana-case-table'>;
}
declare module 'encoding-japanese/src/utf8-to-jis-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/utf8-to-jis-table'>;
}
declare module 'encoding-japanese/src/utf8-to-jisx0212-table.js' {
  declare module.exports: $Exports<'encoding-japanese/src/utf8-to-jisx0212-table'>;
}
declare module 'encoding-japanese/src/util.js' {
  declare module.exports: $Exports<'encoding-japanese/src/util'>;
}
declare module 'encoding-japanese/tests/test.js' {
  declare module.exports: $Exports<'encoding-japanese/tests/test'>;
}
