// flow-typed signature: 48819c96185230c47d1fe5d1ef39be81
// flow-typed version: <<STUB>>/@progress/kendo-react-dropdowns_v^2.6.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@progress/kendo-react-dropdowns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@progress/kendo-react-dropdowns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@progress/kendo-react-dropdowns/dist/cdn/js/kendo-react-dropdowns' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoComplete' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoCompleteProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBox' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBoxProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/ClearButton' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/DropDownBase' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/events' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/filterDescriptor' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/List' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/ListContainer' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/ListDefaultItem' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/ListFilter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/ListItem' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/Navigation' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/SearchBar' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/settings' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/utils' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/common/VirtualScroll' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownList' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownListProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/messages/index' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelect' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelectProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/TagList' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoComplete' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoCompleteProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBox' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBoxProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/ClearButton' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/DropDownBase' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/events' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/filterDescriptor' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/List' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListContainer' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListDefaultItem' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListFilter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListItem' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/Navigation' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/SearchBar' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/settings' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/utils' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/common/VirtualScroll' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownList' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownListProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/messages/index' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelect' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelectProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/TagList' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-dropdowns/dist/systemjs/kendo-react-dropdowns' {
  declare module.exports: any;
}

// Filename aliases
declare module '@progress/kendo-react-dropdowns/dist/cdn/js/kendo-react-dropdowns.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/cdn/js/kendo-react-dropdowns'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoComplete.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoComplete'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoCompleteProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/AutoComplete/AutoCompleteProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBox.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBox'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBoxProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/ComboBox/ComboBoxProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/ClearButton.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/ClearButton'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/DropDownBase.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/DropDownBase'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/events.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/events'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/filterDescriptor.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/filterDescriptor'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/List.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/List'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/ListContainer.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/ListContainer'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/ListDefaultItem.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/ListDefaultItem'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/ListFilter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/ListFilter'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/ListItem.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/ListItem'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/Navigation.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/Navigation'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/SearchBar.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/SearchBar'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/settings.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/settings'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/utils.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/utils'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/common/VirtualScroll.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/common/VirtualScroll'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownList.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownList'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownListProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/DropDownList/DropDownListProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/main'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/messages/index.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/messages/index'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelect.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelect'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelectProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/MultiSelect/MultiSelectProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/es/MultiSelect/TagList.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/es/MultiSelect/TagList'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoComplete.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoComplete'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoCompleteProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/AutoComplete/AutoCompleteProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBox.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBox'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBoxProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/ComboBox/ComboBoxProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/ClearButton.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/ClearButton'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/DropDownBase.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/DropDownBase'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/events.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/events'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/filterDescriptor.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/filterDescriptor'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/List.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/List'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListContainer.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/ListContainer'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListDefaultItem.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/ListDefaultItem'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListFilter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/ListFilter'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/ListItem.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/ListItem'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/Navigation.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/Navigation'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/SearchBar.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/SearchBar'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/settings.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/settings'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/utils.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/utils'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/common/VirtualScroll.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/common/VirtualScroll'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownList.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownList'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownListProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/DropDownList/DropDownListProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/main'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/messages/index.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/messages/index'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelect.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelect'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelectProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/MultiSelect/MultiSelectProps'>;
}
declare module '@progress/kendo-react-dropdowns/dist/npm/MultiSelect/TagList.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/npm/MultiSelect/TagList'>;
}
declare module '@progress/kendo-react-dropdowns/dist/systemjs/kendo-react-dropdowns.js' {
  declare module.exports: $Exports<'@progress/kendo-react-dropdowns/dist/systemjs/kendo-react-dropdowns'>;
}
