// flow-typed signature: d45021d2d166b5e9e8e7e05bb6171746
// flow-typed version: <<STUB>>/@progress/kendo-react-intl_v^2.6.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@progress/kendo-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@progress/kendo-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@progress/kendo-react-intl/dist/cdn/js/kendo-react-intl' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/coreExports' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Intl/IntlProvider' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Intl/IntlProviderProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Intl/IntlService' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Intl/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/intlUtils' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/loadMessages' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationProvider' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationProviderProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationService' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/Localization/messages' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/es/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/coreExports' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlProvider' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlProviderProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlService' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Intl/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/intlUtils' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/loadMessages' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationProvider' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationProviderProps' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationService' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/Localization/messages' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/npm/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-intl/dist/systemjs/kendo-react-intl' {
  declare module.exports: any;
}

// Filename aliases
declare module '@progress/kendo-react-intl/dist/cdn/js/kendo-react-intl.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/cdn/js/kendo-react-intl'>;
}
declare module '@progress/kendo-react-intl/dist/es/coreExports.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/coreExports'>;
}
declare module '@progress/kendo-react-intl/dist/es/Intl/IntlProvider.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Intl/IntlProvider'>;
}
declare module '@progress/kendo-react-intl/dist/es/Intl/IntlProviderProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Intl/IntlProviderProps'>;
}
declare module '@progress/kendo-react-intl/dist/es/Intl/IntlService.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Intl/IntlService'>;
}
declare module '@progress/kendo-react-intl/dist/es/Intl/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Intl/main'>;
}
declare module '@progress/kendo-react-intl/dist/es/intlUtils.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/intlUtils'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/loadMessages.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/loadMessages'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationProvider.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/LocalizationProvider'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationProviderProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/LocalizationProviderProps'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/LocalizationService.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/LocalizationService'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/main'>;
}
declare module '@progress/kendo-react-intl/dist/es/Localization/messages.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/Localization/messages'>;
}
declare module '@progress/kendo-react-intl/dist/es/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/es/main'>;
}
declare module '@progress/kendo-react-intl/dist/npm/coreExports.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/coreExports'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlProvider.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Intl/IntlProvider'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlProviderProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Intl/IntlProviderProps'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Intl/IntlService.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Intl/IntlService'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Intl/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Intl/main'>;
}
declare module '@progress/kendo-react-intl/dist/npm/intlUtils.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/intlUtils'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/loadMessages.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/loadMessages'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationProvider.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/LocalizationProvider'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationProviderProps.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/LocalizationProviderProps'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/LocalizationService.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/LocalizationService'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/main'>;
}
declare module '@progress/kendo-react-intl/dist/npm/Localization/messages.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/Localization/messages'>;
}
declare module '@progress/kendo-react-intl/dist/npm/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/npm/main'>;
}
declare module '@progress/kendo-react-intl/dist/systemjs/kendo-react-intl.js' {
  declare module.exports: $Exports<'@progress/kendo-react-intl/dist/systemjs/kendo-react-intl'>;
}
